var1=float(input("Introduzca un numero:   "))
var2=float(input("Introduzaca otro numero:   "))
print("La suma de ambos es:   ",var1+var2)
print("La resta de ambos es:   ",var1-var2)
print("La multiplicacion de ambos es:   ",var1*var2)
print("La division de ambos es:   ",var1/var2)
print("\n Eso es todo amigos")